// ── Google AI Studio / Gemini integration ──
// One thin call wrapper + prompt builders for each AI feature. When
// GEMINI_API_KEY is absent, callers use a deterministic local fallback so the
// product is still fully explorable.

export type AiMode =
  | "executive_summary"
  | "content_diagnosis"
  | "winning_breakdown"
  | "action_recommendation"
  | "brainstorm"
  | "campaign_planner"
  | "report";

export function geminiConfigured(): boolean {
  return !!process.env.GEMINI_API_KEY;
}

const SYSTEM = `You are the ANTARESTAR Social Media Command Center AI — a senior social-media strategist for an Indonesian outdoor/adventure DTC brand.
You reason with this framework: Objective → Audience → Positioning → Content Funnel (TOFU/MOFU/BOFU/Retention) → Content Pillar → CTA → Data & Iteration.
Be specific, quantitative, and action-oriented. Write in the same language the user's data/question uses (default Bahasa Indonesia mixed with marketing English). Never invent numbers not present in the data. Structure output with short headers and bullet points. End strategic answers with a concrete "Action Plan" of 3-5 steps.`;

export async function callGemini(prompt: string, temperature = 0.6): Promise<string> {
  const key = process.env.GEMINI_API_KEY;
  if (!key) throw new Error("GEMINI_API_KEY not configured");
  const model = process.env.GEMINI_MODEL || "gemini-2.0-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: SYSTEM }] },
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      generationConfig: { temperature, maxOutputTokens: 2048 },
    }),
  });
  if (!res.ok) {
    const b = await res.text();
    throw new Error(`Gemini failed: ${res.status} ${b.slice(0, 200)}`);
  }
  const json = await res.json();
  return (
    json?.candidates?.[0]?.content?.parts?.map((p: any) => p.text).join("") ||
    "No response."
  );
}

export function buildPrompt(mode: AiMode, context: any, question?: string): string {
  const ctx = JSON.stringify(context, null, 0);
  switch (mode) {
    case "executive_summary":
      return `Buat AI Executive Summary dari performa social media ANTARESTAR untuk periode ini.\nData ringkas (JSON): ${ctx}\nSertakan: headline performa, apa yang naik/turun & kenapa, top & worst content, dan 3-5 Action Plan.`;
    case "content_diagnosis":
      return `Diagnosa kenapa konten ini naik/turun. Analisa hook, angle, funnel, pillar, CTA, format, dan metrik.\nKonten (JSON): ${ctx}\nBerikan verdict (naik/turun/stabil), penyebab utama, dan cara memperbaiki/replikasi.`;
    case "winning_breakdown":
      return `Bedah winning content berikut. Untuk tiap konten jabarkan: Hook, Angle, CTA, Format, Durasi/Watch time, kenapa menang, dan template yang bisa direplikasi.\nKonten (JSON): ${ctx}`;
    case "action_recommendation":
      return `Berdasarkan data & insight berikut, berikan rekomendasi action harian & mingguan yang konkret dan terukur.\nData (JSON): ${ctx}`;
    case "brainstorm":
      return `Pertanyaan tim: "${question}"\nGunakan data dashboard berikut untuk menjawab dengan spesifik & berbasis angka.\nData (JSON): ${ctx}`;
    case "campaign_planner":
      return `Ubah insight dashboard menjadi campaign & content plan.\nBrief/pertanyaan: "${question || "Buat plan 1 minggu"}"\nData (JSON): ${ctx}\nOutput: tema campaign, target funnel, daftar konten (hari, akun, pillar, hook, CTA, produk), dan KPI.`;
    case "report":
      return `Buat AI Report ${context?.period || "periode"} lengkap untuk ANTARESTAR.\nData (JSON): ${ctx}\nStruktur WAJIB: 1) Executive Summary 2) What happened 3) Why it happened 4) Winning content 5) Losing content 6) Recommendation 7) Action Plan 8) Next content idea.`;
  }
}

// ── Deterministic local fallback (no API key required) ──
export function localFallback(mode: AiMode, context: any, question?: string): string {
  const a = context?.summary || context?.agg || {};
  const fmt = (n: number) => (n || 0).toLocaleString();
  const insights: any[] = context?.insights || [];
  const bullets = (arr: any[]) =>
    arr.slice(0, 6).map((i) => `- **${i.title}** — ${i.detail}`).join("\n");

  const head = `> ⚙️ *Generated by the built-in analytics engine. Add a \`GEMINI_API_KEY\` in Settings to unlock full Gemini reasoning.*\n`;

  switch (mode) {
    case "executive_summary":
    case "report":
      return `${head}
## Executive Summary
Dalam periode ini ANTARESTAR memproduksi **${fmt(a.posts)} konten**, meraih **${fmt(a.views)} views**, **${fmt(a.reach)} reach**, dan **${fmt(a.engagement)} engagement** (ER ${(a.engagementRate || 0).toFixed(2)}%).

## What happened
- Top content: ${context?.top?.[0]?.hook || "—"}
- Worst content: ${context?.worst?.[0]?.hook || "—"}

## Why it happened
${bullets(insights) || "- Data belum cukup untuk diagnosa mendalam."}

## Recommendation & Action Plan
${bullets(insights.filter((i) => i.severity !== "positive")) || "- Perbanyak konten BOFU & retention."}

## Next content idea
- Replikasi format winning content ke akun affiliate & TikTok.`;
    case "content_diagnosis":
      return `${head}
## Content Diagnosis
- **Verdict:** ${(context?.score || 0) >= 60 ? "Naik / winning" : "Turun / underperform"}
- **Hook:** ${context?.hook}
- **Funnel:** ${context?.funnel} · **Pillar:** ${context?.pillar} · **CTA:** ${context?.cta}
- **Kenapa:** ER ${(context?.engagementRate || 0).toFixed(2)}%, ${fmt(context?.saves)} saves, ${fmt(context?.shares)} shares.
- **Perbaikan:** ${(context?.score || 0) >= 60 ? "Boost & replikasi format ini." : "Ganti hook dengan urgency + perkuat CTA di 3 detik pertama."}`;
    case "winning_breakdown":
      return `${head}
## Winning Content Breakdown
${(context?.items || []).slice(0, 5).map((c: any, i: number) => `**${i + 1}. ${c.hook}**\n- Format: ${c.mediaType} · Watch: ${c.watchTime}s\n- CTA: ${c.cta} · Pillar: ${c.pillar} · Funnel: ${c.funnel}\n- Kenapa menang: ER ${(c.engagementRate || 0).toFixed(1)}%, ${fmt(c.saves + c.shares)} saves+shares.`).join("\n\n")}`;
    case "action_recommendation":
      return `${head}
## Action Recommendation
### Harian
${bullets(insights.filter((i) => i.severity === "positive"))}
### Mingguan
${bullets(insights.filter((i) => i.severity !== "positive"))}`;
    case "brainstorm":
      return `${head}
**Pertanyaan:** ${question}

Berdasarkan data dashboard:
${bullets(insights)}

**Rekomendasi:** fokuskan minggu ini ke funnel yang paling timpang & pillar dengan ER tertinggi. Tambah \`GEMINI_API_KEY\` untuk jawaban brainstorming penuh.`;
    case "campaign_planner":
      return `${head}
## Campaign Plan — ${question || "1 minggu"}
- **Tema:** perkuat BOFU + retention dari winning pillar.
- **Target funnel:** 40% TOFU · 25% MOFU · 25% BOFU · 10% Retention
${(context?.top || []).slice(0, 5).map((c: any, i: number) => `- Hari ${i + 1}: ${c.accountName} · ${c.pillar} · Hook "${c.hook.slice(0, 40)}" · CTA ${c.cta}`).join("\n")}
- **KPI:** ER > ${(a.engagementRate || 1).toFixed(1)}%, +15% saves+shares.`;
  }
}
